import wave
import numpy as np
import matplotlib.pyplot as plt
f_lfo = 10
depth = 1
visualisation_time = 0.5
obj = wave.open("input.wav", "rb")
out_obj = wave.open("output.wav", "wb")
raw_data = obj.readframes(-1)
data = np.frombuffer(raw_data, dtype = np.int16)
n_channels = obj.getnchannels()
sample_rate = obj.getframerate()
n_samples = obj.getnframes()
visualized_samples = int(visualisation_time * sample_rate)
out_obj.setnchannels(n_channels)
out_obj.setsampwidth(2)
out_obj.setframerate(sample_rate)
t = np.arange(n_samples) / sample_rate
if n_channels == 1:
    print("Mono signal")
    y_mono = np.zeros_like(data)
    lfo = 1 + depth * np.sin(2 * np.pi * f_lfo * t)
    y_mono = data * lfo
    y_mono = y_mono / np.max(np.abs(y_mono))
    y_final = (y_mono * 32767).astype(np.int16)
    out_obj.writeframes(y_final.tobytes())
    plt.figure(figsize = (16, 12))
    plt.subplot(2, 1, 1)
    plt.plot(t[:visualized_samples], data[:visualized_samples], color = "blue")
    plt.title("Original Mono Signal")
    plt.xlabel("Time[s]")
    plt.ylabel("Amplitude")
    plt.subplot(2, 1, 2)
    plt.plot(t[:visualized_samples], y_final[:visualized_samples], color = "red")
    plt.title("Tremolo effect applied")
    plt.xlabel("Time[s]")
    plt.ylabel("Amplitude")
    plt.show()
elif n_channels == 2:
    print("Stereo signal")
    data = data.reshape(-1, 2).astype(np.float32)
    y_stereo = np.zeros_like(data)
    lfo = (1 + depth * np.sin(2 * np.pi * f_lfo * t)).reshape(-1, 1)
    y_stereo = data * lfo
    y_stereo = y_stereo / np.max(np.abs(y_stereo))
    y_scaled_stereo = (y_stereo * 32767).astype(np.int16)
    y_final = y_scaled_stereo.flatten()
    out_obj.writeframes(y_final.tobytes())
    plt.figure(figsize = (16, 12))
    plt.subplot(2, 2, 1)
    plt.plot(t[:visualized_samples], data[:, 0][:visualized_samples], color = "green")
    plt.title("Original left channel signal")
    plt.xlabel("Time[s]")
    plt.ylabel("Amplitude")
    plt.subplot(2, 2, 2)
    plt.plot(t[:visualized_samples], data[:, 1][:visualized_samples], color ="green")
    plt.title("Original right channel signal")
    plt.xlabel("Time[s]")
    plt.ylabel("Amplitude")
    plt.subplot(2, 2, 3)
    plt.plot(t[:visualized_samples], y_scaled_stereo[:, 0][:visualized_samples], color = "red") 
    plt.title("Tremolo effect applied to left channel")
    plt.xlabel("Time[s]")
    plt.ylabel("Amplitude")
    plt.subplot(2, 2, 4)
    plt.plot(t[:visualized_samples], y_scaled_stereo[:, 1][:visualized_samples], color = "red")
    plt.title("Tremolo effect applied to right channel")
    plt.xlabel("Time[s]")
    plt.ylabel("Amplitude")
    plt.show()   
out_obj.close()
obj.close()
peak_mono = np.max(np.abs(y_final))
RMS_mono = np.sqrt(np.mean(y_final ** 2))
dB_dynamics = 20 * np.log10(np.abs(y_final) / 32767 + 1e-10)
print(f"Peak amplitude: {peak_mono}.")
print(f"RMS: {RMS_mono}")
print(f"Crest factor: {peak_mono / RMS_mono}")
print(f"Dynamics [dB]: {dB_dynamics}.")
 
    
    